/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'vital-red': '#FF0000',
        'vital-bg': '#F8F9FA',
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#3b3b3b",
        "secondary-fixed": "#c7c6c6",
        "surface-tint": "#5e5e5e",
        "on-primary": "#e2e2e2",
        "outline": "#777777",
        "on-surface": "#1a1c1c",
        "tertiary-container": "#747475",
        "outline-variant": "#c6c6c6",
        "surface-container-high": "#e8e8e8",
        "primary-fixed": "#5e5e5e",
        "on-primary-fixed-variant": "#e2e2e2",
        "primary-container": "#3b3b3b",
        "primary": "#000000",
        "surface-container-highest": "#e2e2e2",
        "secondary": "#5e5e5e",
        "on-primary-fixed": "#ffffff",
        "primary-fixed-dim": "#474747",
        "on-error-container": "#410002",
        "on-secondary-fixed": "#1b1c1c",
        "surface-container": "#eeeeee",
        "background": "#f9f9f9",
        "surface-dim": "#dadada",
        "on-secondary-container": "#1b1c1c",
        "tertiary": "#3a3b3c",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#464747",
        "on-tertiary-fixed-variant": "#e3e2e2",
        "on-tertiary-fixed": "#ffffff",
        "on-tertiary": "#e3e2e2",
        "surface-bright": "#f9f9f9",
        "on-surface-variant": "#474747",
        "surface-container-low": "#f3f3f4",
        "inverse-surface": "#2f3131",
        "secondary-container": "#d5d4d4",
        "error": "#ba1a1a",
        "surface-variant": "#e2e2e2",
        "inverse-primary": "#c6c6c6",
        "inverse-on-surface": "#f0f1f1",
        "error-container": "#ffdad6",
        "surface": "#f9f9f9",
        "on-tertiary-container": "#ffffff",
        "tertiary-fixed": "#5e5e5e",
        "on-primary-container": "#ffffff",
        "on-background": "#1a1c1c",
        "secondary-fixed-dim": "#acabab"
      },
      boxShadow: {
        'card': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
      }
    },
  },
  plugins: [],
}